from __future__ import annotations

from typing import Dict, Tuple

GHANA_OFFICIAL_REGIONS = [
    "Ahafo",
    "Ashanti",
    "Bono",
    "Bono East",
    "Central",
    "Eastern",
    "Greater Accra",
    "Northern",
    "North East",
    "Oti",
    "Savannah",
    "Upper East",
    "Upper West",
    "Volta",
    "Western",
    "Western North",
]

REGION_NORMALIZATION: Dict[str, str] = {
    "ashanti": "Ashanti",
    "ashanti region": "Ashanti",
    "asokwa-kumasi": "Ashanti",
    "ahafo ano south-east": "Ashanti",
    "ejisu municipal": "Ashanti",
    "kwadaso": "Ashanti",
    "mampong": "Ashanti",
    "santasi": "Ashanti",
    "tepa": "Ashanti",
    "bono": "Bono",
    "dormaa east": "Bono",
    "dormaa ahenkro": "Bono",
    "berekum": "Bono",
    "wenchi": "Bono",
    "bono east region": "Bono East",
    "techiman municipal": "Bono East",
    "atebubu": "Bono East",
    "kintampo": "Bono East",
    "ahafo": "Ahafo",
    "ahafo region": "Ahafo",
    "asutifi south": "Ahafo",
    "bechem": "Ahafo",
    "duayaw nkwanta": "Ahafo",
    "central": "Central",
    "central region": "Central",
    "central ghana": "Central",
    "keea": "Central",
    "cape coast": "Central",
    "mankessim": "Central",
    "breman asikuma": "Central",
    "kasoa": "Central",
    "eastern": "Eastern",
    "eastern region": "Eastern",
    "koforidua": "Eastern",
    "akwatia": "Eastern",
    "nkawkaw": "Eastern",
    "akosombo": "Eastern",
    "nsawam": "Eastern",
    "somanya": "Eastern",
    "greater accra": "Greater Accra",
    "greater accra region": "Greater Accra",
    "accra": "Greater Accra",
    "accra east": "Greater Accra",
    "accra north": "Greater Accra",
    "east legon": "Greater Accra",
    "ledzokuku-krowor": "Greater Accra",
    "ga east municipality": "Greater Accra",
    "ga east municipality, greater accra region": "Greater Accra",
    "shai osudoku district, greater accra region": "Greater Accra",
    "tema west municipal": "Greater Accra",
    "osu": "Greater Accra",
    "madina": "Greater Accra",
    "dome": "Greater Accra",
    "nungua": "Greater Accra",
    "dansoman": "Greater Accra",
    "north kaneshie": "Greater Accra",
    "tesano": "Greater Accra",
    "weija": "Greater Accra",
    "oyarifa": "Greater Accra",
    "cantonments": "Greater Accra",
    "adenta": "Greater Accra",
    "haatso": "Greater Accra",
    "maamobi": "Greater Accra",
    "darkuman-nyamekye": "Greater Accra",
    "ashaiman": "Greater Accra",
    "tema": "Greater Accra",
    "northern": "Northern",
    "northern region": "Northern",
    "tamale": "Northern",
    "yendi": "Northern",
    "kpandai": "Northern",
    "north east": "North East",
    "walewale": "North East",
    "oti": "Oti",
    "oti region": "Oti",
    "nkwanta": "Oti",
    "savannah": "Savannah",
    "damongo": "Savannah",
    "upper east": "Upper East",
    "upper east region": "Upper East",
    "bolgatanga": "Upper East",
    "upper west": "Upper West",
    "upper west region": "Upper West",
    "sissala west district": "Upper West",
    "wa": "Upper West",
    "volta": "Volta",
    "volta region": "Volta",
    "central tongu district": "Volta",
    "ho": "Volta",
    "hohoe": "Volta",
    "kpando": "Volta",
    "sogakope": "Volta",
    "adidome": "Volta",
    "akatsi": "Volta",
    "dzodze": "Volta",
    "aflao": "Volta",
    "keta": "Volta",
    "battor": "Volta",
    "western": "Western",
    "western region": "Western",
    "takoradi": "Western",
    "sekondi": "Western",
    "tarkwa": "Western",
    "agona nkwanta": "Western",
    "western north": "Western North",
    "western north region": "Western North",
    "bibiani": "Western North",
    "enchi": "Western North",
    "sefwi wiawso": "Western North",
    "sefwi bekwai": "Western North",
    "sh": "Greater Accra",
}

CITY_TO_REGION: Dict[str, str] = {
    "accra": "Greater Accra",
    "kumasi": "Ashanti",
    "tema": "Greater Accra",
    "takoradi": "Western",
    "sekondi": "Western",
    "tamale": "Northern",
    "cape coast": "Central",
    "sunyani": "Bono",
    "koforidua": "Eastern",
    "ho": "Volta",
    "bolgatanga": "Upper East",
    "wa": "Upper West",
    "techiman": "Bono East",
    "ashaiman": "Greater Accra",
    "tarkwa": "Western",
    "obuasi": "Ashanti",
    "berekum": "Bono",
    "kasoa": "Central",
    "nsawam": "Eastern",
    "kintampo": "Bono East",
    "wenchi": "Bono",
    "yendi": "Northern",
    "sogakope": "Volta",
    "dodowa": "Greater Accra",
    "madina": "Greater Accra",
    "kpando": "Volta",
    "hohoe": "Volta",
    "nkawkaw": "Eastern",
    "akosombo": "Eastern",
    "walewale": "North East",
    "bechem": "Ahafo",
    "nkwanta": "Oti",
    "dzodze": "Volta",
    "aflao": "Volta",
    "keta": "Volta",
    "mankessim": "Central",
    "somanya": "Eastern",
    "tema west": "Greater Accra",
    "oyarifa": "Greater Accra",
    "weija": "Greater Accra",
}

GHANA_CITY_COORDS: Dict[str, Tuple[float, float]] = {
    "accra": (5.6037, -0.1870),
    "kumasi": (6.6885, -1.6244),
    "tema": (5.6698, -0.0166),
    "takoradi": (4.9016, -1.7831),
    "sekondi": (4.9340, -1.7137),
    "tamale": (9.4075, -0.8533),
    "cape coast": (5.1053, -1.2466),
    "sunyani": (7.3349, -2.3123),
    "koforidua": (6.0897, -0.2591),
    "ho": (6.6008, 0.4713),
    "bolgatanga": (10.7867, -0.8514),
    "wa": (10.0601, -2.5019),
}

REGION_CAPITALS: Dict[str, str] = {
    "Ahafo": "Goaso",
    "Ashanti": "Kumasi",
    "Bono": "Sunyani",
    "Bono East": "Techiman",
    "Central": "Cape Coast",
    "Eastern": "Koforidua",
    "Greater Accra": "Accra",
    "Northern": "Tamale",
    "North East": "Nalerigu",
    "Oti": "Dambai",
    "Savannah": "Damongo",
    "Upper East": "Bolgatanga",
    "Upper West": "Wa",
    "Volta": "Ho",
    "Western": "Sekondi",
    "Western North": "Sefwi Wiawso",
}

REGION_CENTROIDS: Dict[str, Tuple[float, float]] = {
    region: GHANA_CITY_COORDS.get(capital.lower())
    for region, capital in REGION_CAPITALS.items()
}

SOURCE_TYPE_MAP: Dict[str, str] = {
    "facebook.com": "social",
    "fb.com": "social",
    "linkedin.com": "social",
    "ghanayello.com": "directory",
    "ghanabusinessweb.com": "directory",
    "africabizinfo.com": "directory",
    "vymaps.com": "directory",
    "medpages.info": "directory",
    "ghanahospitals.org": "registry",
    "chstgh.org": "registry",
    "hefra.gov.gh": "government",
    "ghaneps.gov.gh": "government",
}

SOURCE_PRIORITY: Dict[str, int] = {
    "official": 1,
    "government": 2,
    "registry": 2,
    "directory": 3,
    "social": 4,
    "blog": 4,
    "unknown": 5,
}
